### ISSUE TITLE
JivaVolumePolicy - should allow to skip parameters with internal default values. 

### ISSUE THREAD

**Issue by kmova** [openebs/jiva-operator#128]
This is to see if any of the fields in the jiva volume policies are incorrectly set as mandatory. for example "enableBufio" and "autoScaling" are good candidates for optional fields - with internally set default values. 

```
apiVersion: openebs.io/v1alpha1
kind: JivaVolumePolicy
metadata:
  name: jiva-policy-mongo
  namespace: openebs
spec:
  replicaSC: openebs-hostpath
  enableBufio: false
  autoScaling: false
  target:
    replicationFactor: 1
    monitor: true
```
